Repository klingo/ESO-PersonalAssistant, pull requests merged in 2020-10, with the labels that each got.

#265 PA: profile management
  PersonalAssistant/Menu/MainMenu.lua
  PersonalAssistant/Menu/MenuFunctions.lua
  PersonalAssistant/Menu/MenuHelper.lua
  PersonalAssistant/PersonalAssistant.lua
  PersonalAssistant/PersonalAssistant.txt
  PersonalAssistant/PersonalAssistantBanking/PersonalAssistantBanking.lua
  PersonalAssistant/PersonalAssistantIntegration/Menu/PAIntegrationMenuDefaults.lua
  PersonalAssistant/PersonalAssistantIntegration/PersonalAssistantIntegration.lua
  PersonalAssistant/PersonalAssistantJunk/PersonalAssistantJunk.lua
  PersonalAssistant/PersonalAssistantLoot/PersonalAssistantLoot.lua
  PersonalAssistant/PersonalAssistantRepair/PersonalAssistantRepair.lua
  PersonalAssistant/Utilities/HelperFunctions.lua
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
  PersonalAssistant/Utilities/XML/RulesWindow.lua
  PersonalAssistant/bindings/Bindings.lua
  PersonalAssistant/bindings/Bindings.xml
  PersonalAssistant/localization/de.lua
  PersonalAssistant/localization/en.lua
  PersonalAssistant/localization/fr.lua
  PersonalAssistant/localization/ru.lua
  PersonalAssistant/vars/Globals.lua
  info/description.txt
  info/images/PAG.png
  info/images/PAG.txt
Labels: enhancement

#266 PAL: fixed an issue with 'known' icon for items/containers without traits
  PersonalAssistant/PersonalAssistantLoot/PALoot/PALootItemIcons.lua
Labels: bug

#267 PA: APIVersion 100033 (Markarth) supported
  PersonalAssistant/PersonalAssistant.txt
  PersonalAssistant/PersonalAssistantBanking/PABanking/PABanking.lua
  PersonalAssistant/PersonalAssistantBanking/PersonalAssistantBanking.txt
  PersonalAssistant/PersonalAssistantIntegration/PersonalAssistantIntegration.txt
  PersonalAssistant/PersonalAssistantJunk/PersonalAssistantJunk.txt
  PersonalAssistant/PersonalAssistantLoot/PersonalAssistantLoot.txt
  PersonalAssistant/PersonalAssistantRepair/PersonalAssistantRepair.txt
Labels: enhancement

#268 PAJ: dont mark crafted items
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenu.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuDefaults.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuFunctions.lua
  PersonalAssistant/PersonalAssistantJunk/PAJunk/PAJunk.lua
  PersonalAssistant/PersonalAssistantJunk/localization/de.lua
  PersonalAssistant/PersonalAssistantJunk/localization/en.lua
  PersonalAssistant/PersonalAssistantJunk/localization/fr.lua
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
  PersonalAssistant/vars/Globals.lua
Labels: enhancement

#269 PAJ: Stolen Solvents
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenu.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuDefaults.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuFunctions.lua
  PersonalAssistant/PersonalAssistantJunk/PAJunk/PAJunk.lua
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
  PersonalAssistant/localization/de.lua
  PersonalAssistant/localization/en.lua
  PersonalAssistant/localization/fr.lua
Labels: enhancement

#270 PAJ: fixed "ignore mailbox items" setting
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuFunctions.lua
Labels: bug

#271 PAJ: Stolen Trash
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenu.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuDefaults.lua
  PersonalAssistant/PersonalAssistantJunk/Menu/PAJunkMenuFunctions.lua
  PersonalAssistant/PersonalAssistantJunk/PAJunk/PAJunk.lua
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
Labels: enhancement

#272 PAJ: Fix double marking item as junk
  PersonalAssistant/PersonalAssistantJunk/PAJunk/PAJunk.lua
Labels: bug

#273 Russian localization for version 2.5.0
  PersonalAssistant/PersonalAssistantJunk/localization/ru.lua
  PersonalAssistant/localization/ru.lua
Labels: enhancement

#274 PA: localization refactor
  PersonalAssistant/PersonalAssistantBanking/localization/de.lua
  PersonalAssistant/PersonalAssistantBanking/localization/fr.lua
  PersonalAssistant/PersonalAssistantBanking/localization/ru.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/de.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/en.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/fr.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/ru.lua
  PersonalAssistant/PersonalAssistantJunk/localization/de.lua
  PersonalAssistant/PersonalAssistantJunk/localization/fr.lua
  PersonalAssistant/PersonalAssistantJunk/localization/ru.lua
  PersonalAssistant/PersonalAssistantLoot/localization/de.lua
  PersonalAssistant/PersonalAssistantLoot/localization/en.lua
  PersonalAssistant/PersonalAssistantLoot/localization/fr.lua
  PersonalAssistant/PersonalAssistantLoot/localization/ru.lua
  PersonalAssistant/PersonalAssistantRepair/localization/de.lua
  PersonalAssistant/PersonalAssistantRepair/localization/en.lua
  PersonalAssistant/PersonalAssistantRepair/localization/fr.lua
  PersonalAssistant/PersonalAssistantRepair/localization/ru.lua
  PersonalAssistant/localization/de.lua
  PersonalAssistant/localization/fr.lua
  PersonalAssistant/localization/ru.lua
Labels: refactoring

#275 PA: updated French translations from Takit
  PersonalAssistant/PersonalAssistantJunk/localization/fr.lua
  PersonalAssistant/PersonalAssistantRepair/localization/fr.lua
  PersonalAssistant/localization/fr.lua
Labels: enhancement

#276 PAB: fixed wrong itemID for Dominion Battering Ram
  PersonalAssistant/vars/Globals.lua
Labels: bug

#277 PA minor cleanup
  PersonalAssistant/Menu/ItemContextMenu.lua
  PersonalAssistant/PersonalAssistant.txt
  PersonalAssistant/Utilities/HelperFunctions.lua
  PersonalAssistant/Utilities/XML/RulesWindow.lua
Labels: refactoring

#278 PA: fixed an issue where non-EN localizations were not applied
  PersonalAssistant/PersonalAssistantBanking/localization/de.lua
  PersonalAssistant/PersonalAssistantBanking/localization/fr.lua
  PersonalAssistant/PersonalAssistantBanking/localization/ru.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/de.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/fr.lua
  PersonalAssistant/PersonalAssistantIntegration/localization/ru.lua
  PersonalAssistant/PersonalAssistantJunk/localization/de.lua
  PersonalAssistant/PersonalAssistantJunk/localization/fr.lua
  PersonalAssistant/PersonalAssistantJunk/localization/ru.lua
  PersonalAssistant/PersonalAssistantLoot/localization/de.lua
  PersonalAssistant/PersonalAssistantLoot/localization/fr.lua
  PersonalAssistant/PersonalAssistantLoot/localization/ru.lua
  PersonalAssistant/localization/de.lua
  PersonalAssistant/localization/fr.lua
  PersonalAssistant/localization/ru.lua
Labels: bug

#279 PAJ: standard items only marked as junk if 'new'
  PersonalAssistant/PersonalAssistantJunk/PAJunk/PAJunk.lua
Labels: refactoring

#280 PAL: fixed an issue where the known/unknown icon was no longer shown for containers
  PersonalAssistant/PersonalAssistantLoot/PALoot/PALootItemIcons.lua
Labels: bug

#291 PAB: fixed an issue with mass-update moveMode for survey reports
  PersonalAssistant/PersonalAssistantBanking/Menu/PABankingMenuFunctions.lua
Labels: bug

#292 PAB: add holiday writs (replacing 'invalid' master writs)
  PersonalAssistant/PersonalAssistantBanking/Menu/PABankingMenu.lua
  PersonalAssistant/PersonalAssistantBanking/Menu/PABankingMenuDefaults.lua
  PersonalAssistant/PersonalAssistantBanking/Menu/PABankingMenuFunctions.lua
  PersonalAssistant/PersonalAssistantBanking/PABanking/PABankingAdvanced.lua
  PersonalAssistant/PersonalAssistantBanking/localization/en.lua
  PersonalAssistant/Utilities/HelperFunctions.lua
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
  PersonalAssistant/vars/Globals.lua
Labels: enhancement

#293 PAL: fixed an issue where regular loot containers got flagged as 'unknown'
  PersonalAssistant/PersonalAssistantLoot/PALoot/PALootItemIcons.lua
Labels: bug

#294 PAB: fixes a rare(?) issue with holidayWrits from migrating to 2.5.4
  PersonalAssistant/Utilities/SavedVarsPatcher.lua
  PersonalAssistant/vars/Globals.lua
Labels: bug
